app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/


use App\Place;
Route::group(['middleware' => ['auth','admin']], function () {
    Route::get('/','RepliesController@indexNote');
    Route::resource('conditions', 'ConditionsController');
    Route::resource('daily_times', 'Daily_timesController');
    Route::resource('hotels', 'HotelsController');
    Route::resource('maintenance_rooms', 'Maintenance_roomsController');
    Route::resource('members', 'MembersController');
    Route::resource('notes', 'NotesController');
    Route::resource('places', 'PlacesController');
    Route::resource('replies', 'RepliesController');
    Route::resource('reports', 'ReportsController');
    Route::resource('report_details', 'Report_detailsController');
    Route::resource('rooms', 'RoomsController');
    Route::resource('room_types', 'Room_typesController');
    Route::resource('statuses', 'StatusesController');
    Route::resource('tasks', 'TasksController');
    Route::resource('times', 'TimesController');
    Route::resource('users', 'UsersController');

    //メール送信テスト用
    Route::get('/email_sending_test', function (){
        $data = [
            'title'=>'Infomation from H-Core',
            'content'=>'This is message below.'
        ];
        Mail::send('emails.test', $data, function($message){
            $message->to('t.morishita@takingshape.co','Tsutomu Morishita')->subject('Infomation');
        });
    });

    // タイムカード
    Route::get('time_card',[
        'as' => 'time_card',
        'uses' => 'TimesController@indexTimeCard'
    ]);
    Route::get('create_time_card/{member_id}',[
        'as' => 'create_time_card',
        'uses' => 'TimesController@createTimeCard'
    ]);
    Route::post('store_time_card',[
        'as' => 'store_time_card',
        'uses' => 'TimesController@storeTimeCard'
    ]);
    Route::get('create_pass/{member_id}',[
        'as' => 'create_pass',
        'uses' => 'TimesController@createPass'
    ]);
    Route::post('store_pass/{id}',[
        'as' => 'store_pass',
        'uses' => 'TimesController@storePass'
    ]);
    Route::get('change_pass/{member_id}',[
        'as' => 'change_pass',
        'uses' => 'TimesController@changePass'
    ]);
    Route::post('update_pass/{id}',[
        'as' => 'update_pass',
        'uses' => 'TimesController@updatePass'
    ]);
    Route::get('input_pass/{id}',[
        'as' => 'input_pass',
        'uses' => 'TimesController@inputPass'
    ]);
    Route::post('check_pass',[
        'as' => 'check_pass',
        'uses' => 'TimesController@checkPass'
    ]);
    //伝言掲示板
    Route::get('show_note/{id}',[
        'as' => 'show_note',
        'uses' => 'RepliesController@showNote'
    ]);
    Route::get('index_note',[
        'as' => 'index_note',
        'uses' => 'RepliesController@indexNote'
    ]);
    Route::get('create_note/{id}',[
        'as' => 'create_note',
        'uses' => 'RepliesController@createNote'
    ]);
    Route::post('store_note',[
        'as' => 'store_note',
        'uses' => 'RepliesController@storeNote'
    ]);
    Route::delete('delete_note/{id}',[
        'as' => 'delete_note',
        'uses' => 'RepliesController@deleteNote'
    ]);
    Route::get('create_master_note',[
        'as' => 'create_master_note',
        'uses' => 'NotesController@createMasterNote'
    ]);
    Route::post('store_master_note',[
        'as' => 'store_master_note',
        'uses' => 'NotesController@storeMasterNote'
    ]);
    Route::delete('delete_master_note/{id}',[
        'as' => 'delete_master_note',
        'uses' => 'NotesController@deleteMasterNote'
    ]);
    //部屋情報
    Route::get('index_room',[
        'as' => 'index_room',
        'uses' => 'RoomsController@indexRoom'
    ]);
    Route::post('store_task',[
        'as' => 'store_task',
        'uses' => 'TasksController@storeTask'
    ]);

//ホテル側部屋情報入力
    Route::get('create_order_room',[
        'as' => 'create_order_room',
        'uses' => 'RoomsController@createOrderRoom'
    ]);
    Route::get('create_order_room2/{date}',[
        'as' => 'create_order_room2',
        'uses' => 'RoomsController@createOrderRoom2'
    ]);
    Route::post('store_order_room',[
        'as' => 'store_order_room',
        'uses' => 'TasksController@storeOrderRoom'
    ]);
    Route::get('index_finish_room',[
        'as' => 'index_finish_room',
        'uses' => 'RoomsController@indexFinishRoom'
    ]);
    Route::post('store_finish_room',[
        'as' => 'store_finish_room',
        'uses' => 'TasksController@storeFinishRoom'
    ]);

//勤怠集計
    Route::get('index_all_times',[
        'as' => 'index_all_times',
        'uses' => 'Daily_timesController@indexAllTimes'
    ]);
    Route::post('index_all_times2',[
        'as' => 'index_all_times2',
        'uses' => 'Daily_timesController@indexAllTimes2'
    ]);

    Route::get('index_sales',[
        'as' => 'index_sales',
        'uses' => 'PlacesController@indexSales'
    ]);

//シフト登録
    Route::get('index_shift/{place_id}',[
        'as' => 'index_shift',
        'uses' => 'MembersController@indexShift'
    ]);

    Route::post('update_shift',[
        'as' => 'update_shift',
        'uses' => 'MembersController@updateShift'
    ]);

//地図表示
    Route::get('map',[
        'as' => 'map',
        'uses' => 'PlacesController@map'
    ]);

//会議用（一時的メニュー表示）
    Route::get('tmp_room_input',[
        'as' => 'tmp_room_input',
        'uses' => 'RoomsController@tmpRoomInput'
    ]);

    // 報告集計
    Route::get('index_daily_report',[
        'as' => 'index_daily_report',
        'uses' => 'ReportsController@indexDailyReport'
    ]);
    Route::post('index_daily_report2',[
        'as' => 'index_daily_report2',
        'uses' => 'ReportsController@indexDailyReport2'
    ]);

    //User パスワード変更
    Route::get('edit_pass/{id}',[
        'as' => 'edit_pass',
        'uses' => 'UsersController@editPass'
    ]);
    Route::put('update_pass/{id}',[
        'as' => 'update_pass',
        'uses' => 'UsersController@updatePass'
    ]);
});

    // Authentication routes...
    Route::get('auth/login', 'Auth\AuthController@getLogin');
    Route::post('auth/login', 'Auth\AuthController@postLogin');
    Route::get('auth/logout', 'Auth\AuthController@getLogout');

    // Registration routes...
    Route::get('auth/register', 'Auth\AuthController@getRegister');
    Route::post('auth/register', 'Auth\AuthController@postRegister');

    // パスワードリセットリンクを要求するルート…
    Route::get('password/email', 'Auth\PasswordController@getEmail');
    Route::post('password/email', 'Auth\PasswordController@postEmail');

    // パスワードリセットルート
    Route::get('password/reset/{token}', 'Auth\PasswordController@getReset');
    Route::post('password/reset', 'Auth\PasswordController@postReset');

    //作業報告
    Route::get('create_daily_report',[
        'as' => 'create_daily_report',
        'uses' => 'ReportsController@createDailyReport'
    ]);
    Route::get('edit_daily_report',[
        'as' => 'edit_daily_report',
        'uses' => 'ReportsController@editDailyReport'
    ]);
    Route::post('check_daily_report',[
        'as' => 'check_daily_report',
        'uses' => 'ReportsController@checkDailyReport'
    ]);
    Route::post('store_daily_report',[
        'as' => 'store_daily_report',
        'uses' => 'ReportsController@storeDailyReport'
    ]);
    Route::put('update_daily_report',[
        'as' => 'update_daily_report',
        'uses' => 'ReportsController@updateDailyReport'
    ]);

app/Reply.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Reply extends Model
{
    use SoftDeletes;
    public function note()
    {
        return $this->belongsTo('App\Note');
    }
    public function member()
    {
        return $this->belongsTo('App\Member');
    }

    protected $fillable = [
        'note_id',
        'member_id',
        'note_reply',
    ];
}

app/Http/Controllers/RepliesController.php
<?php

namespace App\Http\Controllers;

use App\Member;
use App\Note;
use App\Place;
use App\Reply;
use Auth;
use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

class RepliesController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        $replies = Reply::all();
        return view('replies.index', compact('replies'));
    }
    
    public function create()
    {
        $notes = Note::all();
        $members = Member::all();
        return view('replies.create', compact('notes','members'));
    }
    
    public function store(Request $request)
    {
        Reply::create($request->all());
        return redirect('/replies');
    }

    public function show($id)
    {
        $reply = Reply::findOrFail($id);
        return view('replies.show', compact('reply'));
    }

    public function edit($id)
    {
        $reply = Reply::findOrFail($id);
        $notes = Note::all();
        $members = Member::all();
        return view('replies.edit', compact('reply','notes','members'));
    }

    public function update(Request $request, $id)
    {
        $reply = Reply::findOrFail($id);
        $reply -> update($request -> all());
        return redirect("/replies");
    }

    public function destroy($id)
    {
        $reply = Reply::findOrFail($id);
        $reply->delete();
        return redirect('/replies');
    }

    public function showNote($id)
    {
        $place_id = Auth::user()->place_id;
        $note = Note::find($id);
        $member = Member::find($note->member_id);
        $place = Place::find($note->place_id);
        $replies = Reply::all()->where('note_id',$id)->sortByDesc('created_at');
        return view('replies.show_note', compact('replies','note','member','place', 'auth_member','place_id'));
    }

    public function createNote($id)
    {
        $user_id = Auth::user()->id;

        $members = Member::All()->where('user_id', $user_id)->sortBy('last_name_kana');
        $note = Note::find($id);
        $member = Member::find($note->member_id);
        $place = Place::find($note->place_id);
        $replies = Reply::all()->where('note_id',$id)->sortByDesc('created_at');
        return view('replies.create_note', compact('replies','note','member','place','members','id'));
    }

    public function storeNote(Request $request)
    {
        Reply::create($request->all());
        return redirect()->route('show_note', [$request->note_id]);
    }

    public function indexNote()
    {
        if(Auth::check()) {
            if(Auth::user()->authority_id == 4) {
                return redirect('/create_daily_report');
            }
        }
        $place_id = Auth::user()->place_id;
        $notes1 = Note::where('place_id',$place_id);
        $notes = Note::where('place_id',1)->union($notes1)->get()->sortByDesc('created_at');
        return view('replies.index_note', compact('notes'));
    }

    public function deleteNote($id)
    {
        $reply = Reply::findOrFail($id);
        $note_id = $reply->note_id;
        $reply->delete();
        return redirect()->route('show_note', [$note_id]);
    }
}

resources/views/replies/create.blade.php
@extends('layouts.app')
@section('content')
    <h1>新規登録</h1>
    <form method="post" action="/replies">
        <div class="form-group">
            <label>返信する記事：</label>
            <select name="note_id" class="form-control">
                @if($notes)
                    @foreach($notes as $note)
                        <option value="{{$note->id}}">{{$note->title}}</option>
                    @endforeach
                @endif
            </select>
        </div>
        <div class="form-group">
            <label>返信内容：</label>
            <textarea name="note_reply" placeholder="返信内容を入力してください。" rows="4" class="form-control" id="InputTextarea"></textarea>
        </div>
        <div class="form-group">
            <label>投稿者：</label>
            <select name="member_id" class="form-control">
                @if($members)
                    @foreach($members as $member)
                        <option value="{{$member->id}}">{{$member->last_name}} {{$member->first_name}}</option>
                    @endforeach
                @endif
            </select>
        </div>
        {{csrf_field()}}
        <div class="pull-right">
            <a href="{{route('replies.index')}}" class="btn btn-default" role="button">戻る</a>
            <button type="submit" class="btn btn-primary">登録</button>
        </div>
    </form>
@stop

resources/views/replies/create_note.blade.php
@extends('layouts.app')
@section('content')
    <a class="btn btn-default" href="{{route('index_note')}}">戻る</a>
    <hr>
    <h1>{{$note->title}}</h1>
    <p class="text-right"><strong>{{$place->name}}</strong> {{$member->last_name}} {{$member->first_name}} <span style="padding-left: 20px; color: #999999">{{$note->created_at->diffForhumans()}}</span></p>
    <div style="padding: 20px;background-color: #f5f5f5;border: 1px solid #ccc;border-radius: 4px;color: #333;">{{$note->note}}</div>
    <hr>
    <form method="post" action="/store_note">
        {{csrf_field()}}
        <input name="note_id" type="hidden" value="{{$id}}">
        <div class="form-group">
            <label>名前</label>
            <select name="member_id" class="form-control">
                @if($members)
                    @foreach($members as $member)
                        <option value="{{$member->id}}">{{$member->last_name}} {{$member->first_name}}</option>
                    @endforeach
                @endif
            </select>
        </div>
        <div class="form-group" style="margin-bottom: 0">
            <label>コメント</label>
            <textarea name="note_reply" placeholder="追加するコメントを入力してください。" rows="3" class="form-control" id="InputTextarea"></textarea>
        </div>
        <button type="submit" class="btn btn-primary pull-right" style="margin-top: 20px">追 加</button>
    </form>
    <div style="margin-top: 80px">
    @if($replies)
        @foreach($replies as $reply)
            <div style="width:100%;margin-top: 20px;margin-bottom: 40px">
                <p style="font-size: 13px"><strong>{{$reply->member->place->name}}</strong> {{$reply->member->last_name}} {{$reply->member->first_name}} <span style="color: #999999;padding-left: 20px">{{$reply->created_at->diffForhumans()}}</span></p>
                <div>
                    {{$reply->note_reply}}
                </div>
            </div>
        @endforeach
    @endif
    </div>
@stop

resources/views/replies/edit.blade.php
@extends('layouts.app')
@section('content')
    <h1>登録変更</h1>
    <form method="post" action="/replies/{{$reply->id}}">
        {{csrf_field()}}
        <input type="hidden" name="_method" value="PUT">
        <div class="form-group">
            <label>返信する記事：</label>
            <select name="note_id" class="form-control">
                @if($notes)
                    @foreach($notes as $note)
                        <option value="{{$note->id}}"
                                @if ($note->id == old('note_id'))
                                selected="selected"
                                @endif
                        >{{$note->title}}</option>
                    @endforeach
                @endif
            </select>
        </div>
        <div class="form-group">
            <label>返信内容：</label>
            <textarea name="note_reply" placeholder="返信内容を記述してください。" rows="4" class="form-control" id="InputTextarea">{{$reply->note_reply}}</textarea>
        </div>
        <div class="form-group">
            <label>投稿者：</label>
            <select name="member_id" class="form-control">
                @if($members)
                    @foreach($members as $member)
                        <option value="{{$member->id}}"
                                @if ($member->id == old('member_id'))
                                selected="selected"
                                @endif
                        >{{$member->last_name}} {{$member->first_name}}</option>
                    @endforeach
                @endif
            </select>
        </div>
        <div class="pull-right">
            <a href="{{route('replies.index')}}" class="btn btn-default" role="button">戻る</a>
            <button type="submit" class="btn btn-primary">更新</button>
        </div>
    </form>
    <div class="pull-left">
        <form method="post" action="{{route('replies.show', $reply->id)}}">
            {{csrf_field()}}
            <input type="hidden" name="_method" value="DELETE">
            <button type="submit" class="btn btn-danger">削除</button>
        </form>
    </div>
@stop

resources/views/replies/index.blade.php
@extends('layouts.app')
@section('content')
    <h1>一覧</h1>
    <div class="pull-right">
        <a href="{{route('replies.create')}}" class="btn btn-primary" role="button">新規登録</a>
    </div>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>返信ID</th>
                <th>返信する投稿</th>
                <th>返信内容</th>
                <th>投稿者</th>
                <th>更新日時</th>
                <th>登録日時</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        @if($replies)
            @foreach($replies as $reply)
                <tr>
                    <td>{{$reply->id}}</td>
                    <td>{{$reply->note->title}}</td>
                    <td>{{$reply->note_reply}}</td>
                    <td>{{$reply->member->last_name}} {{$reply->member->first_name}}</td>
                    <td>{{$reply->updated_at->diffForhumans()}}</td>
                    <td>{{$reply->created_at->diffForhumans()}}</td>
                    <td>
                        <div class="pull-right">
                            <a href="{{route('replies.show', $reply->id)}}" class="btn btn-default" role="button">詳細</a>
                            <a href="{{route('replies.edit', $reply->id)}}" class="btn btn-primary" role="button">変更</a>
                        </div>
                    </td>
                </tr>
            @endforeach
        @endif
        </tbody>
    </table>
@stop

resources/views/replies/index_note.blade.php
@extends('layouts.app')
@section('content')
    <h1>伝言ノート</h1>
    <div class="pull-right">
        <a href="{{route('create_master_note')}}" class="btn btn-primary" role="button">新規登録</a>
    </div>
    <table class="table table-striped">
        <thead>
            <tr>
                <th></th>
                <th>タイトル</th>
                <th>登録日時</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        @if($notes)
            @foreach($notes as $note)
                <tr>
                    <td>
                        @if($note->place_id == 1)
                            <div style="text-align:center;padding:7px;border-radius: 3px;background-color: #337ab7;color:#ffffff">{{$note->place->name}}</div>
                        @else
                            <div style="text-align:center;padding:7px;border-radius: 3px;color:#337ab7;border:1px solid #337ab7">{{$note->place->name}}</div>
                        @endif
                    </td>
                    <td style="font-weight: bold">
                        <a href="{{route('show_note', $note->id)}}" style="font-weight: bold">{{$note->title}}</a>
                    </td>
                    <td>{{$note->created_at->diffForhumans()}}</td>
                    <td>
                        <div class="pull-right">
                            <a href="{{route('show_note', $note->id)}}" class="btn btn-default" role="button">詳細</a>
                            {{--<a href="{{route('notes.edit', $note->id)}}" class="btn btn-primary" role="button">変更</a>--}}
                        </div>
                    </td>
                </tr>
            @endforeach
        @endif
        </tbody>
    </table>
@stop

resources/views/replies/show.blade.php
@extends('layouts.app')
@section('content')
    <h1>詳細</h1>
    <table class="table">
        <tbody>
            <tr>
                <th>返信ID</th>
                <td>{{$reply->id}}</td>
            </tr>
            <tr>
                <th>返信する投稿</th>
                <td>{{$reply->note->title}}</td>
            </tr>
            <tr>
                <th>返信内容</th>
                <td>{{$reply->note_reply}}</td>
            </tr>
            <tr>
                <th>報告者</th>
                <td>{{$reply->member->last_name}} {{$reply->member->first_name}}</td>
            </tr>
            <tr>
                <th>更新日時</th>
                <td>{{$reply->updated_at->diffForhumans()}}</td>
            </tr>
            <tr>
                <th>登録日時</th>
                <td>{{$reply->created_at->diffForhumans()}}</td>
            </tr>
        </tbody>
    </table>
    <div class="pull-right">
        <a href="{{route('notes.index')}}" class="btn btn-default" role="button">戻る</a>
        <a href="{{route('notes.edit', $reply->id)}}" class="btn btn-primary" role="button">変更</a>
    </div>
@stop

resources/views/replies/show_note.blade.php
@extends('layouts.app')
@section('content')
    <a class="btn btn-default" href="{{route('index_note')}}">戻る</a>
    <hr>
    <h1>{{$note->title}}</h1>
    <p class="text-right"><strong>{{$place->name}}</strong> {{$member->last_name}} {{$member->first_name}} <span style="padding-left: 20px; color: #999999">{{$note->created_at->diffForhumans()}}</span></p>
    <div style="white-space:pre-wrap;padding: 20px;background-color: #f5f5f5;border: 1px solid #ccc;border-radius: 4px;color: #333;">{{$note->note}}</div>
    <div style="margin-top: 20px">
        @if($place_id == $note->place_id)
            <form method="post" action="{{route('delete_master_note', $note->id)}}">
                {{csrf_field()}}
                <input type="hidden" name="_method" value="DELETE">
                <button type="submit" class="btn btn-danger">削除</button>
            </form>
        @endif
    </div>
    <div class="pull-right">
        <a class="btn btn-primary text-right" href="{{route('create_note', $note->id)}}" style="margin-top: 20px">コメントを追加する</a>
    </div>
    <div style="margin-top: 80px">
    @if($replies)
        @foreach($replies as $reply)
            <div style="width:100%;margin-top: 20px;margin-bottom: 40px">
                <p style="font-size: 13px"><strong>{{$reply->member->place->name}}</strong> {{$reply->member->last_name}} {{$reply->member->first_name}} <span style="color: #999999;padding-left: 20px">{{$reply->created_at->diffForhumans()}}</span></p>
                <div>
                    {{$reply->note_reply}}
                </div>
                @if($place_id == $reply->member->place_id)
                <form method="post" action="{{route('delete_note', $reply->id)}}">
                    {{csrf_field()}}
                    <input type="hidden" name="_method" value="DELETE">
                    <button type="submit" class="btn btn-default" style="border:none;padding:0;font-size: 10px;text-decoration: underline;color:red;">削除</button>
                </form>
                @endif
            </div>
        @endforeach
    @endif
    </div>
@stop